[package]
name = "linux-nvme-sys"
version = "0.2.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"
description = "Rust bindgen for nvme on linux"
license = "MIT"
repository = "https://github.com/MOZGIII/linux-nvme-sys"

[dependencies]
nix = "0.15"

[build-dependencies]
bindgen = "0.51"
